[project]
name = "bili23-downloader"
version = "1.66.0"
description = "跨平台的 B 站视频下载工具，支持 Windows、Linux、macOS 三平台，下载 B 站视频/番剧/电影/纪录片 等资源"
readme = "README.md"
license = "MIT License"
requires-python = ">=3.9"
dependencies = [
    "qrcode[pil]==7.4.2",
    "requests==2.32.5",
    "wxpython==4.2.3",
    "python-vlc==3.0.21203",
    "protobuf==6.32.0",
    "websockets==15.0.1",
    "pycryptodome==3.23.0"
]
authors = [
    {name = "ScottSloan", email = "scottsloan@petalmail.com"},
]
encoding = "utf-8"

[project.scripts]
bili23-gui = "GUI"